### ISSUE TITLE
[Web player] Small black box for mouse cursor in game window

### ISSUE THREAD

**Issue by dxgldotorg** [ZQuestClassic/ZQuestClassic#922]
The mouse cursor when it's supposed to be hidden is replaced with a small black box.  Running ZC Web Player 3.0.0-prerelease.49+2024-04-06, on Chrome Dev, Windows 11 24H2 Insider Preview, NVIDIA driver 552.12.

**Comment by dxgldotorg** [comment]
Additional info:  Display resolution 3840x2160, scaling set to 200% in case that's needed to reproduce the glitch.

**Comment by ksyfhater** [comment]
> The mouse cursor when it's supposed to be hidden is replaced with a small black box. Running ZC Web Player 3.0.0-prerelease.49+2024-04-06, on Chrome Dev, Windows 11 24H2 Insider Preview, NVIDIA driver 552.12.

did u find a solution? i have this and i cant find a solution

**Comment by dxgldotorg** [comment]
Never did, hence why I posted an Issue.

**Comment by connorjclark** [comment]
Don't have a specific fix for this nor can I repro. But I have seen this sort of thing before. I think it was kinda rare for me, and got resolved after changing window focus (or maybe it required a page reload). But I haven't seen it in awhile.

Just now I've updated the web version to `3.0.0-prerelease.105+2025-05-19` (you may need to clear cache to see - can confirm by looking at the About dialog). That comes with a lot of updates to SDL and other stuff we use, so perhaps that will resolve it for you two.

If not: please open the browser devtools console and share any console messages you see, could be relevant.

**Comment by dxgldotorg** [comment]
Here's the console output:
```
The FetchEvent for "https://www.googletagmanager.com/gtag/js?id=G-36Y8HGSBRW" resulted in a network error response: the promise was rejected.
Promise.then
(anonymous) @ Router.js:58
play/:568 
            
            
           GET https://www.googletagmanager.com/gtag/js?id=G-36Y8HGSBRW net::ERR_FAILED
NetworkFirst.js:120 Uncaught (in promise) no-response: no-response :: [{"url":"https://www.googletagmanager.com/gtag/js?id=G-36Y8HGSBRW"}]
    at v.I (https://web.zquestclassic.com/workbox-ac292ed5.js:1:8298)
    at async v.R (https://web.zquestclassic.com/workbox-ac292ed5.js:1:7159)
I @ NetworkFirst.js:120
await in I
R @ Strategy.js:144
await in R
handleAll @ Strategy.js:135
handle @ Strategy.js:96
handleRequest @ Router.js:197
(anonymous) @ Router.js:56
injection-topics.js:1 Browsing Topics API removed
play/:1 Banner not shown: beforeinstallpromptevent.preventDefault() called. The page must call beforeinstallpromptevent.prompt() to show the banner.
zplayer.js:1 Initializing Allegro... SFX.Dat...OK
zplayer.js:1 [Deprecation] The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead. (https://bit.ly/audio-worklet)
2013989 @ zplayer.js:1
runMainThreadEmAsm @ zplayer.js:1
_emscripten_asm_const_int_sync_on_main_thread @ zplayer.js:1
$EMSCRIPTENAUDIO_OpenDevice @ zplayer.wasm:0xb95ce0
$open_audio_device @ zplayer.wasm:0x391b30
$sdl_allocate_voice @ zplayer.wasm:0x7d4829
$al_reserve_samples @ zplayer.wasm:0x57b5e8
$a5_sound_init @ zplayer.wasm:0x99ed23
$main @ zplayer.wasm:0x87a1e5
ret.<computed> @ zplayer.js:1
doRewind @ zplayer.js:1
(anonymous) @ zplayer.js:1
zplayer.js:1 Initializing sound driver... OK
zplayer.js:1 Fonts.Dat...ZC Launched: ZQuest Classic Player, 3.0.0-prerelease.105+2025-05-19
zplayer.js:1 OK
zplayer.js:1 OK
zplayer.js:1 Initializing music... OK
zplayer.js:1 set gfx mode succsessful at -2 8bpp 640 x 480 
zplayer.js:1 Loading Saved Games
zplayer.js:1 Finished Loading Saved Games
zplayer.js:1 Loading qst: modules/classic/title_gfx.dat
zplayer.js:1 Time to load qst: 255 ms
```
